### ISSUE TITLE
YAML to orchestrate terraform 

### ISSUE THREAD

**Issue by dotcomputercraft** [infrablocks/terraform-aws-ecs-cluster#14]
Hello,

I was wondering how you use the YAML defined in terraform-aws-ecs-cluster/config/defaults.yaml to invoke the terraforn init ..., terraforn plan ..., terraform apply ... 

I love to use YAML to orchestrate terraform *.tfvar values.  Thank you in advance.

Best regards,

John Montoya

**Comment by jonassvalin** [comment]
Hi @dotcomputercraft 
We use rake and a number of rake libraries that we've built (rake-terraform for example) to drive our build tools, combined with hiera for resolving configuration. See the Rakefile and hiera configuration for more details.

Thanks
