### ISSUE TITLE
Allow encryption to be enabled for root EBS volume

### ISSUE THREAD

**Issue by tobyclemson** [infrablocks/terraform-aws-ecs-cluster#24]

**Comment by jeroenhabets** [comment]
@tobyclemson I checked our ECS EC2's launched from this module all have encryption at rest enabled on their root volume. Am I missing something?

**Comment by tobyclemson** [comment]
Hi @jeroenhabets,

Hmm, that's strange, according to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration#root_block_device the default for `encrypted` is `false` and this module doesn't currently override that or allow it to be overridden by the module consumer.

Could it be possible you have this enabled: https://aws.amazon.com/premiumsupport/knowledge-center/ebs-automatic-encryption/ and that's causing the volumes to be encrypted?

Thanks,
Toby

**Comment by tobyclemson** [comment]
@jonassvalin does your recent release resolve this issue?

**Comment by jonassvalin** [comment]
This is indeed fixed in release [6.0.0](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.0.0).
