### ISSUE TITLE
Allow setting default capacity provider for cluster

### ISSUE THREAD

**Issue by ezpuzz** [infrablocks/terraform-aws-ecs-cluster#25]
The default capacity provider is not being set so you must set at the service level.

Also the outputs do not include the capacity provider name, only the autoscaling group.

`aws_ecs_service` can be passed the capacity provider name and it would be nice to have it available

**Comment by jonassvalin** [comment]
Thanks for your issue @ezpuzz , I'll have a look at the request.

**Comment by jonassvalin** [comment]
I've had a look at your request, and we're currently using Terraform AWS version 3.x, but we would like to upgrade to version 4.x at some point. If we do upgrade, the capacity provider configuration will behave differently, but is it enough to solve your problem now in the short term if we attach the created asg_capacity_provider as the default one? Keep in mind that when we do have to upgrade to version 4.x it will likely be a breaking change.

Separately we can also output the capacity provider name, if that is useful.

**Comment by jonassvalin** [comment]
@ezpuzz I will close this for now since I haven't heard anything, but feel free to re-open if you decide that the solution I proposed above is workable for you
