### ISSUE TITLE
Module not working on Mac with M1 (darwin_arm64)

### ISSUE THREAD

**Issue by fullheart** [infrablocks/terraform-aws-ecs-cluster#30]
# Problem
When I install this module (with `terraform init`) on my MacBook Pro with M1 processor, I get **`Incompatible provider version`**.

_See full error message_
![image](https://user-images.githubusercontent.com/25485618/169827058-2bea9d3d-7641-418e-967e-0c54cfe8b6f7.png)

# Analyze
The problem is, that this module use HasiCorp's deprecated [`Template Provider`](https://registry.terraform.io/providers/hashicorp/template/latest/docs). Because it's deprecated, HashiCorp don't provide a binary for `darin_arm64` (known as Apple's M1 processor).

# Solution
Use instead of `data "template_file` blocks Terraforms `locals` block with `templatefile` function.

**Comment by fullheart** [comment]
Here a pull reqeuest to resolve the problem: https://github.com/infrablocks/terraform-aws-ecs-cluster/pull/31

**Comment by eric-millin** [comment]
Please fix this

**Comment by Gryff** [comment]
This was resolved in version `4.2.0`. I'll close this now along with the corresponding PR.
