### ISSUE TITLE
Detailed monitoring default enabled

### ISSUE THREAD

**Issue by rajbasnet0007** [infrablocks/terraform-aws-ecs-cluster#33]
After the creation of the new cluster, it enabled default detailed monitoring of EC2 instances, which caused the high AWS bill.
![image](https://user-images.githubusercontent.com/36179005/180410253-af46b239-2fde-4642-84d5-a04bb75b0309.png)

**Comment by tobyclemson** [comment]
Hi @rajbasnet0007,

This is the default for the `aws_launch_configuration` resource. We'd happily accept a PR to disable this if you're willing to put one together.

Thanks,
Toby

**Comment by rajbasnet0007** [comment]
yes, please disable the detailed monitoring default. we unable to disable it by default

**Comment by andrei-dascalu** [comment]
@tobyclemson @rajbasnet0007 merge request in progress

**Comment by jonassvalin** [comment]
This has now been resolved in PR #71

**Comment by tobyclemson** [comment]
Bear in mind that we have left the detailed monitoring enabled by default for backwards compatibility so to disable it, you'd need to pass the `enable_detailed_monitoring` var as `false`.
