### ISSUE TITLE
Allow KMS encryption for root EBS volume default

### ISSUE THREAD

**Issue by rajbasnet0007** [infrablocks/terraform-aws-ecs-cluster#35]
Hi Team
Default root volume encryption for the cluster on rest is disabled. The infoblocks cluster supports no input argument for root volume encryption.

**Comment by rajbasnet0007** [comment]
HI Team 

Could you please fix this issue?
We are using the same module for production servers and the default EBS root volume is unencrypted and we are unable to add in code.

**Comment by tobyclemson** [comment]
@jonassvalin is this one resolved with your latest release?

**Comment by jonassvalin** [comment]
This is indeed fixed in release [6.0.0](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.0.0).
