### ISSUE TITLE
Auto scaling basis of CPU utilization provision new EC2 and send notification email

### ISSUE THREAD

**Issue by rajbasnet0007** [infrablocks/terraform-aws-ecs-cluster#38]
How can integrate the SNS topic with the autoscaling group in this ECS module and send a notification if new EC2 server provisioned

**Comment by jonassvalin** [comment]
Hi @rajbasnet0007 ,
The problem you're describing would likely require custom work. If you're interested in buying some of our services for implementing this, please get in contact through our [website](https://go-atomic.io/) and we can look at how we can support you for this use case.

Best regards
Jonas
