### ISSUE TITLE
Use aws_launch_template instead of aws_launch_configuration

### ISSUE THREAD

**Issue by ragumix** [infrablocks/terraform-aws-ecs-cluster#42]
Hello!

Due to AWS recommendations to use aws_launch_template instead of aws_launch_configuration looks like it needs to change this module a little bit.
https://docs.aws.amazon.com/autoscaling/ec2/userguide/create-launch-config.html

Even in the page of Launch configurations there is a message with recommendation:
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/39560105/197209522-b4c45f6c-5dfb-4c69-9033-2439533b0ac2.png">

**Comment by Gryff** [comment]
Hi @ragumix 
This is on our radar, we're doing some modernisation work on all our tf modules right now (using `nullable`, using `optional`, converting from `"yes" / "no"` to booleans, and when that's done we'll tackle this request 👍

**Comment by jeroenhabets** [comment]
@Gryff Thanks for all the great work! Chiming in here as my team and stakeholders are getting a bit worried about the ever more persistent AWS mails and health alerts about this deprecation. Do you happen to have an ETA on aws_launch_configuration support? Regards, Jeroen

**Comment by jonassvalin** [comment]
@jeroenhabets We don't have an ETA at the moment, but we intend to get to it before the deadline. We would however be very open to a PR, as we have other competing priorities as well.

As a side note, we do offer a paid support contract model in which we provide immediate help with any InfraBlocks related queries. If you want to explore it you can find more information at https://go-atomic.io/products/infrablocks/pricing/ .

**Comment by jonassvalin** [comment]
This has now been resolved in ersion 5.0.0, see https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/5.0.0 . Please consult the CHANGELOG for details on breaking changes.
