### ISSUE TITLE
[Feedback] CHANGELOG.md 4.2.0 already allowed using the Terraform AWS provider v4?

### ISSUE THREAD

**Issue by jeroenhabets** [infrablocks/terraform-aws-ecs-cluster#60]
Hi @tobyclemson,

Thanks for all the great work!

FYI: I noticed an inaccuracy in [CHANGELOG.md](https://github.com/infrablocks/terraform-aws-ecs-cluster/blob/main/CHANGELOG.md#500-december-22nd-2022):

The following are listed under "5.0.0 (December 22nd 2022)"
> IMPROVEMENTS
    This module no longer requires the template provider.
    This module now allows using the Terraform AWS provider v4.

But we've been using Terraform AWS provider v4 with your module successfully for a while now. Also #34 indicates it's part of 4.2.0 so I think at least the 2nd line should move there.

BTW: 4.2.0 also already contains a line regarding "the template provider."

Furthermore I'd list also "Support for [AWS Launch templates](https://docs.aws.amazon.com/autoscaling/ec2/userguide/launch-templates.html) (fixes  #42)" as an (or even the major) improvement (not just the backward warning).

Cheers, Jeroen
P.S. I hope this is the right way and tone to communicate feedback.

**Comment by jonassvalin** [comment]
Thanks @jeroenhabets , this has now been [resolved](https://github.com/infrablocks/terraform-aws-ecs-cluster/blob/main/CHANGELOG.md#500-december-22nd-2022).
