### ISSUE TITLE
Ignoring changes to cluster_desired_capacity following autoscaling activities

### ISSUE THREAD

**Issue by andrei-dascalu** [infrablocks/terraform-aws-ecs-cluster#69]
Currently it seems to me that subsequent applies will always try to set the desired capacity to either what was provided during initial setup or the default '3' if the setting is removed.

This is really bad when the autoscaling group has changed the size between min and max but then the apply will try to take it back to whatever it was.

case in point, I have a cluster with min = 2, max = 12. It creates a cluster with 3 instances. Later on my workload leads to the cluster increasing to 6. Now whenever I apply I have to make sure to manually update the desired count to whatever it is at that time.

Suggestion:
no default desired value. If nothing is provided then the cluster should ignore lifecycle changes to the desired capacity (it will spin up base on min instance count anyway).

**Comment by tobyclemson** [comment]
Hey @andrei-dascalu,

Thanks for raising, I think it would be great to get this solved and I think your suggestion makes sense.

Would you be willing to create a PR for this?

Thanks,
Toby

**Comment by jeroenhabets** [comment]
@tobyclemson (@andrei-dascalu ) I just created a PR for it instead: #93

**Comment by jeroenhabets** [comment]
> version [6.1.0-rc.2](https://registry.terraform.io/modules/infrablocks/ecs-cluster/aws/6.1.0-rc.2) includes this change.
