### ISSUE TITLE
subnet_ids should be a list

### ISSUE THREAD

**Issue by shmick** [infrablocks/terraform-aws-ecs-cluster#7]
Since subnet_ids is always a list when dealing with AWS resources, it would be ideal if this module also accepted it as a list so that a single subnet_ids list var can be used in a tfvars file.

Changing ```cluster.tf``` so that ```vpc_zone_identifier = "${split(",", var.subnet_ids)}"``` becomes ```vpc_zone_identifier = "${join(",", var.subnet_ids)}"``` should work.  

I'm currently using this within the module ```subnet_ids = join(", ", var.subnet_ids_private)``` in order to use my already defined list var.

**Comment by tobyclemson** [comment]
Hi Steve,

This is a hangover from when terraform didn't support list type variables on modules.

Whilst this represents a breaking change to the interface, I'd be happy to accept a pull request and can bump by a major version to indicate the change.

Thanks,
Toby

**Comment by tobyclemson** [comment]
This is resolved in the latest release.
