### ISSUE TITLE
The module produces 2 attached volumes of 30 Gb with default settings

### ISSUE THREAD

**Issue by andrei-dascalu** [infrablocks/terraform-aws-ecs-cluster#74]
When creating a cluster with default settings, I have instances with 2 volumes specified in the definition:

1. `/dev/xvda` - 30 Gb, root volume
2. `/dev/sda1` - 30 Gb, additional volume

I'm not quite sure what to make of it

**Comment by tobyclemson** [comment]
Hi @andrei-dascalu 

Good find, it seems the Amazon Linux 2 base image has changed the location of its root volume. We'll need to investigate to work out the best course of action, unless you have a suggestion?

Thanks,
Toby

**Comment by andrei-dascalu** [comment]
@tobyclemson perhaps a quick win could be to make the volume a parameter. Not sure what a good default would be, maybe the old value as a default (or the current AWS root volume?).

**Comment by jonassvalin** [comment]
This has now been resolved in PR #71

**Comment by andrei-dascalu** [comment]
@tobyclemson @jonassvalin I've tested the latest RC and looks good. When applying with new settings as defaults, no change is detected and I was able to get the expected results (setting the log retention limit, disable enhanced monitoring as well as specifying the root volume - resulting in a single volume on the launch template).

**Comment by jonassvalin** [comment]
@andrei-dascalu Great, thanks. The full release of 5.1.0 is now available.
