### ISSUE TITLE
Feature request: launch_template options a.o IMDSv2 to prevent Server Side Request Forgery (SSRF) (OWASP Top-10)

### ISSUE THREAD

**Issue by jeroenhabets** [infrablocks/terraform-aws-ecs-cluster#79]
As happy users of your module, we are also  very happy about the recently introduced EC2 [launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template) support (#42), quite a few, for us, important [launch_template](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template) options cannot be configured (see also [asg.tf](https://github.com/infrablocks/terraform-aws-ecs-cluster/blob/main/asg.tf#L23-L59))

- `metadata_options` in particular `http_tokens` to prevent IMDSv2 to improve Server Side Request Forgery (SSRF) Prevention (OWASP Top-10). <= my driver to file this issue.
- `tag_specifications` in particular to be able to tag the cluster worker volumes in our case for our compliance and cost management.

Looking forward to your response! TIA!

P.S. Sources for IMDSv2 to prevent Server Side Request Forgery (SSRF) (OWASP Top-10) :
- https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_%28SSRF%29/
- https://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/

**Comment by jonassvalin** [comment]
Hi @jeroenhabets 
Your suggestions make sense, would you like to open a PR for them? The tags currently passed to the module could be passed directly to the tag_specifications.

For the metadata_options I suggest passing an object with potentially optional strings depending on what is or isn't required for the variable. This is slightly inconsistent with the rest of the module as we historically used individual vars rather than objects before they were available in Terraform, but it's the way we're moving with new module development.

Best regards
Jonas

**Comment by jeroenhabets** [comment]
Hi @jonassvalin, Great! I'll discuss this with my Ops Lead (@rovnik) and come back to you! Jeroen

**Comment by jeroenhabets** [comment]
@jonassvalin One PR #94 for missing volume tags

**Comment by jeroenhabets** [comment]
@jonassvalin (@tobyclemson ) and PR #94 that:

> Resolves main part of https://github.com/infrablocks/terraform-aws-ecs-cluster/issues/79 a.o. IMDSv2 to prevent Server Side Request Forgery (SSRF) (OWASP Top-10)
>
> Introduces new cluster_instance_metadata_options module parameter to control [launch_template.metadata-options](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#metadata-options) with secure default.
> See also [Use IMDSv2](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) and [Add defense in depth against open firewalls, reverse proxies, and SSRF vulnerabilities with enhancements to the EC2 Instance Metadata Service](http://aws.amazon.com/blogs/security/defense-in-depth-open-firewalls-reverse-proxies-ssrf-vulnerabilities-ec2-instance-metadata-service/)

I agree with @jonassvalin:
> As far as default value goes, we tend to lean towards the most secure possible defaults.

NOTE: In CHANGELOG.md we should warn users of this module of this change in the unlikely event they (still) can not utilize IMDSv2

**Comment by tobyclemson** [comment]
Both PRs are now merged so I'm going to close this issue. Thanks for your contributions!
