### ISSUE TITLE
cluster_instance_ssh_public_key_path should be optional

### ISSUE THREAD

**Issue by shmick** [infrablocks/terraform-aws-ecs-cluster#8]
It's good security to not have ssh key pairs associated with instances if they absolutely don't need them. I'd like to suggest that ```cluster_instance_ssh_public_key_path``` be made optional, rather than required.

Thanks.

**Comment by tobyclemson** [comment]
Hi Steve,

Agreed, this would be great to have. Would you be able to put together a pull request for this?

Thanks,
Toby
